on: push

jobs:
  lint-readme:
    name: Lint README.md
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint README.md
      uses: avtodev/markdown-lint@v1
      with:
        #rules: '/lint/rules/changelog.js'
        #config: '/lint/config/changelog.yml'
        args: './README.md'
