name: "Lint README.md markdown"
on: 
  pull_request:
  push:
    branches:
      - live

jobs:
  lint-readme:
    name: Lint README 
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint README
      uses: docker://avtodev/markdown-lint:v1 
      with:
        args: './README.md'

