on: push

jobs:
  build:
    runs-on: ubuntu-latest
    - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
            # config_file: .markdownlint.yaml
            # ignore_files: examples/ignore/*
            # ignore_path: examples/.markdownlintignore
            # rules: examples/rules/custom.js
